name: arm64-3

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: show git head
      run: git --no-pager show HEAD
    - name: bootstrap vcpkg
      run: bootstrap-vcpkg.bat
    - name: show git head
      run: git --no-pager show HEAD
    - name: install libs
      run: vcpkg.exe install sdl2:arm64-windows sdl2-image:arm64-windows sdl2-mixer:arm64-windows
    - uses: actions/upload-artifact@master
      with:
        name: scummvm-package
        path: D:\a\vcpkg3\vcpkg3\installed
      if: always()
