name: arm64-openexr

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: show git head
      run: git --no-pager show HEAD
    - name: bootstrap vcpkg
      run: bootstrap-vcpkg.bat
    - name: show git head
      run: git --no-pager show HEAD
    - name: install libs
      run: vcpkg.exe install openexr:arm64-windows
    - name: show logs
      run: type D:\a\vcpkg3\vcpkg3\buildtrees\openexr\install-arm64-windows-dbg-out.log
      if: failure()
    - uses: actions/upload-artifact@master
      with:
        name: scummvm-package
        path: D:\a\vcpkg3\vcpkg3\installed
      if: always()
