name: arm64

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: show git head
      run: git --no-pager show HEAD
    - name: bootstrap vcpkg
      run: bootstrap-vcpkg.bat
    - name: clone scummvm
      run: git clone https://github.com/janisozaur/scummvm
    - name: show git head
      run: git --no-pager show HEAD
    - name: install boost-build
      run: vcpkg.exe install boost-build
    - name: install libs
      run: vcpkg.exe install libpng:arm64-windows freetype:arm64-windows curl:arm64-windows libjpeg-turbo:arm64-windows sdl2:arm64-windows sdl2-net:arm64-windows libvorbis:arm64-windows libmad:arm64-windows libogg:arm64-windows libflac:arm64-windows libtheora:arm64-windows fluidsynth:arm64-windows
    - name: build scummvm-dbg
      run: |
        mkdir scummvm/build-dbg
        cd scummvm/build-dbg
        cmake -DCMAKE_TOOLCHAIN_FILE=D:/a/vcpkg3/vcpkg3/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows .. -A Arm64
        cmake --build
        echo janis building
        cmake --build . -j --config Debug
        cd ../../
    - name: build scummvm-rel
      run: |
        mkdir scummvm/build-rel
        cd scummvm/build-rel
        cmake -DCMAKE_TOOLCHAIN_FILE=D:/a/vcpkg3/vcpkg3/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=arm64-windows .. -A Arm64
        cmake --build
        echo janis building
        cmake --build . -j --config Release
        cd ../../
    - name: package
      run: |
        mkdir scummvm-package
        cp scummvm/build-rel/Release/scummvm.exe scummvm-package/scummvm-rel.exe
        cp scummvm/build-dbg/Debug/scummvm.exe scummvm-package/scummvm-dbg.exe
    - uses: actions/upload-artifact@master
      with:
        name: scummvm-package
        path: D:\a\vcpkg3\vcpkg3\scummvm-package
      if: always()
